### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by barseghyanartur** [adamchainz/rst-improved#1]
Does this work?

Adding repository (just this github link: https://github.com/adamchainz/sublime-rst-improved) and then looking up for the package in the install package list by name (RestructuredText Improved) does not show up anything.

SubimeText version: 3.2.2
OS: Fedora 33

**Comment by adamchainz** [comment]
The listing was merged to package control just the other day: https://github.com/wbond/package_control_channel/pull/8197

I just checked and it seems the package is [listed](https://packagecontrol.io/packages/RestructuredText%20Improved) but pending review to re-enable it. I have asked about getting it re-enabled on that thread.
