### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by evdcush** [adamchainz/rst-improved#2]
Adam, thank you for forking and reviving this package! 🙏🏻 

I've moved on to VSC for most of my needs now, but with rst, it was really this sole package that made editing reStructuredText tenable.

 
The original package got lost, and I've been copying over the assets from older machines to keep this plugin going. Really appreciate that you made the effort to revive it! 🥰

**Comment by adamchainz** [comment]
Glad to help!
