### ISSUE TITLE
Adding support for `code-block` directive

### ISSUE THREAD

**Issue by javiereguiluz** [adamchainz/rst-improved#3]
Thanks a lot for taking care of maintaining this package 🙏 

I'm trying to add support for code block highlighting. It's similar to the current `preformatted-content`, but instead of guessing the programming language, it's defined explicitly:

```rst
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam:

.. code-block:: yaml

    # some YAML code here

Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.

.. code-block:: html

    <!-- some HTML content here -->
```

The `code-block` directive is very common when writing tech docs because it comes from Sphinx, which is commonly used when using RST. See https://sublime-and-sphinx-guide.readthedocs.io/en/latest/code_blocks.html

I tried the following but it's not working. Any help would be much appreciated.

First I add this:

```xml
<key>codeblock_yaml</key>
<dict>
    <key>applyEndPatternLast</key>
    <integer>1</integer>
    <key>begin</key>
    <string>^([\x{00000020}\t]*)(\.\.)\s+(code\-block(?::[\w\-]+)*)(::)\s+yaml</string>
    <key>beginCaptures</key>
    <dict>
        <key>2</key>
        <dict>
            <key>name</key>
            <string>keyword.operator.restructuredtext.directive</string>
        </dict>
        <key>3</key>
        <dict>
            <key>name</key>
            <string>keyword.restructuredtext.directive</string>
        </dict>
        <key>4</key>
        <dict>
            <key>name</key>
            <string>keyword.operator.restructuredtext.directive</string>
        </dict>
    </dict>
    <key>contentName</key>
    <string>string.unquoted.heredoc.preformatted.yaml.restructuredtext</string>
    <key>end</key>
    <string>^(?:(?!\1[\x{00000020}\t])|(?=\1[\x{00000020}\t]+:|\s*$))</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>source.yaml</string>
        </dict>
    </array>
</dict>
```

And then I add this:

```xml
<key>block</key>
<dict>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#codeblock_yaml</string>
        </dict>
        <!-- ... -->
</dict>
```

I'd appreciate a lot if you could give me some clue about how to make this work. Thanks a lot for your time!

**Comment by adamchainz** [comment]
Hi, I'm afraid I have no idea how to make it work. I only revived this package in order to get it working for myself, since I wanted to recommend it to a friend. I would like to merge some bits in upstream at https://github.com/sublimehq/Packages .

I'm sure the inline thing is possible - the markdown definition already does this in sublime IIRC so check in the upstream `Packages` repo for some clues. If you get it working I'd look at your PR!

**Comment by javiereguiluz** [comment]
Thanks for your comment and sorry for my late reply.
